version: "3.9"

services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27017
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: flights_backend
    container_name: flightsBackend
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  frontend:
    build:
      context: ./src/main/frontend
      dockerfile: Dockerfile
    image: flights_frontend
    container_name: flightsFrontend
    ports:
      - 3000:3000